language: python
python:
  - "3.5"
# command to set environment
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script:main.py
